### ISSUE TITLE
Perfectionist's Checklist

### ISSUE THREAD

**Issue by abitrolly** [urfave/cli#1612]
Here are some things that I found internally unsatisfying in `v2`.

* [x] I want to turn off `help` command
* [ ] I want `App.Name` to be `AppName` to make it clear it is only used in help formatting
* [x] No need to say that default for help is `false` (`--help, -h  show help (default: false)`)
    #1633
* [x] Don't say that my program accepts arguments when it doesn't (`sub add [command options] [arguments...]`)
* [x] Don't say subcommand accepts options when it doesn't (`sub add [command options] [arguments...]`)
* [x] Fail with an error if user supplies arguments that are not supported
    #1797

To be expanded..

* [ ] Allow `Name: "--password"` and `Name: "-p, --password"` to simplify grep for looking where options are defined
* [x] Make subcommand `-h` take priority over missing required flag on level above

## What problem does this solve?

Reaching inner peace.

**Comment by dearchap** [comment]
@abitrolly I agree with all of these points. In fact these have been raised before see

https://github.com/urfave/cli/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fv3

However at this point v2 is in maintenance mode so no new features/functionality. Most if not all of your issues are slated to be fixed in v3. Why v3 you say ? We wanted to take the most requested features and create a new version of the software . As part of this we've rewritten the flag code to use generics so that feature addition is localized and more manageable than it is currently. For example see the recent changes for persistent flags in v3. It required an update to just 4 files vs currently we would have to update almost 15-20 files. So code maintenance is better . That being said are you up for these changes coming to v3?

**Comment by abitrolly** [comment]
I don't understand generics, and I don't know how much time it will be needed for me to get it, but when `v3` is ready to be used, I can easily go through this checklist to see if it works for me.

**Comment by abitrolly** [comment]
@dearchap renamed feature request template to point to `v3` https://github.com/urfave/cli/pull/1613

**Comment by dearchap** [comment]
Thanks @abitrolly

**Comment by dearchap** [comment]
@abitrolly I like the idea of having a single ```Name: "-p,  --password" ``` rather than aliases. I think v1 had support for this. @urfave/cli WDYT ?

**Comment by dearchap** [comment]
@abitrolly I've discussed with @meatballhat offline and we are going to keep the same Name/Aliases structure and not go back to ```"-p, --password"``` style. I think we've covered all the items issues listed in this issue. Closing for now

**Comment by abitrolly** [comment]
@dearchap thanks for taking this in the works. )
